// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA87Apu_rGxLy1Dc3z2AWUE6CUoC3vVUpg',
    appId: '1:754431644910:web:c9efb1800edf398a168fff',
    messagingSenderId: '754431644910',
    projectId: 'quickdoodle-e386e',
    authDomain: 'quickdoodle-e386e.firebaseapp.com',
    databaseURL: 'https://quickdoodle-e386e-default-rtdb.firebaseio.com',
    storageBucket: 'quickdoodle-e386e.firebasestorage.app',
    measurementId: 'G-9S5VDCF0B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSWe3L59UQOE55TmgbJUStsUdBpNYToC0',
    appId: '1:754431644910:android:8880fff0adc18187168fff',
    messagingSenderId: '754431644910',
    projectId: 'quickdoodle-e386e',
    databaseURL: 'https://quickdoodle-e386e-default-rtdb.firebaseio.com',
    storageBucket: 'quickdoodle-e386e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxGmzOsV8xJHupNYfnvtbCGC-rH9k1GvY',
    appId: '1:754431644910:ios:acc0191a980c593c168fff',
    messagingSenderId: '754431644910',
    projectId: 'quickdoodle-e386e',
    databaseURL: 'https://quickdoodle-e386e-default-rtdb.firebaseio.com',
    storageBucket: 'quickdoodle-e386e.firebasestorage.app',
    iosBundleId: 'com.example.lovedGorod',
  );
}
